baseurl = "http://dstroot.github.io/my-hugo-blog"
publishdir = "docs"
title = "Dan Stroot"
languageCode = "en-us"
theme = "hyde-x"
paginate = 5
canonifyurls = true

[params]
  googleAnalytics = ""
  # themeColor = "theme-base-0d"
  # If false display full article contents in blog index.
  # Otherwise show description and 'read on' link to individual blog post page.
  # Default (if omitted) is true.
  truncate = true
  tagline = "I love building things. Made in California. Family man, technologist and Hacker News aficionado. Eternally curious."
  disqusShortname = "danstroot"
  gravatarHash = "b6e0ed5e10ea91f67808629f4ae109f2"
  github = "https://github.com/dstroot"
  linkedin = "https://www.linkedin.com/in/danstroot"
  facebook = "https://www.facebook.com/dan.stroot"
  twitter = "https://twitter.com/danstroot"

[author]
  name = "Dan Stroot"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/blog/:year/:month/:day/:title/"
