baseurl = "http://dstroot.github.io/my-hugo-blog/"
publishdir = "docs"
title = "Dan Stroot"
languageCode = "en-us"
theme = "hyde"
paginate = 5
canonifyurls = true

[params]
  themeColor = "theme-base-0d"
  description = "I love building things. Made in California. Family man, technologist and Hacker News aficionado. Eternally curious."
