baseURL = "https://danstroot.com"
publishDir = "docs"
title = "Blog"
languageCode = "en-us"
enableEmoji = true
theme = "hugo"
paginate = 5
canonifyURLs = true
disqusShortname = "danstroot"
googleAnalytics = "UA-44765020"

# [blackfriday]
#   angledQuotes = false
#   # fractions = false
#   # plainIDAnchors = true
#   smartQuotes = true
#   extensions = ["laxHtmlBlocks"]

[params]
  truncate = true
  tagline = "I love building things. Made in California. Family man, technologist and Hacker News aficionado. Eternally curious."
  gravatarHash = "b6e0ed5e10ea91f67808629f4ae109f2"
  github = "https://github.com/dstroot"
  linkedin = "https://www.linkedin.com/in/danstroot"
  facebook = "https://www.facebook.com/dan.stroot"
  twitter = "https://twitter.com/danstroot"
  highlight = "github"

[author]
  name = "Dan Stroot"

[permalinks]
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/:year/:month/:day/:title/"

# [taxonomies]
#     # Optional. Use if you want tags and lists.
#     category = "categories"
